### ISSUE TITLE
SyntaxError: Unexpected token '﻿' at 1:1 when using config file

### ISSUE THREAD

**Issue by motohead400** [webextensions/copy-files-from-to#10]
Attached is my config file (renamed to .txt). When I try to run "copy-files-from-to" it gives me an error of: Get SyntaxError: Unexpected token '﻿' at 1:1
[copy-files-from-to.txt](https://github.com/webextensions/copy-files-from-to/files/3208502/copy-files-from-to.txt)

I don't think there's any problem with my config file. I also tried running it with the exact sample config file and still got the same error. I'm using version 1.2.0 of copy-files-from-to and nodejs version: 10.15.1

**Comment by webextensions** [comment]
@motohead400 
The config file is saved in "UTF-8 with BOM" mode. As a workaround, you may save the file in normal "UTF8" mode and it would work fine.

I'll make a fix to handle that encoding to resolve the issue.

**Comment by webextensions** [comment]
@motohead400 
Try using copy-files-from-to@1.2.1 now. It should work fine for your file as well.
