### ISSUE TITLE
Request: Ability to consider only the last part of "from" when using glob

### ISSUE THREAD

**Issue by zeniale** [webextensions/copy-files-from-to#11]
Actually if i configure the .json file like this:
```sh
{
	"copyFiles": [
		{
			"from": "node_modules/@fortawesome/fontawesome-free/webfonts/**/*",
			"to": "wwwroot/content/webfonts/"
		}
	]
}
```
I obtain a folder strucure like this:
![image](https://user-images.githubusercontent.com/5589516/59018020-341dcd00-8845-11e9-88da-c0dc0d08eb08.png)

It is possible to ignore the part before glob?
I like to have a folder structure like this:
![image](https://user-images.githubusercontent.com/5589516/59018081-59124000-8845-11e9-9db9-be620a00a36c.png)

Thanks

**Comment by webextensions** [comment]
@zeniale
Try out this feature with copy-files-from-to@1.3.0 now :-)

Please use the "toFlat" parameter:
```js
// Copy the files matching the "glob" pattern
// (all of the matching files directly go into the
// "to" directory) since "toFlat" is set to "true"
{
    "from": "assets/**/*.jpg",
    "to": "public/copy-all-jpg-files-to-this-directory/",
    "toFlat": true
}
```

**Comment by zeniale** [comment]
Wonderful, it's work fine.
Thank you!!!
