### ISSUE TITLE
Fails to copy some files when destination is just a directory 

### ISSUE THREAD

**Issue by vinodloha** [webextensions/copy-files-from-to#12]
For a copy operation with config like below:
```
{
      "from": "../src/*.*",
      "to": "../runtime/"
},
{
      "from": "../src/*.{html, js, json}",
      "to": "../runtime/"
},
```

Output is: 
✓ Copied [ utf8 ] src/googlebd585bdbe4d612c7.html to runtime/5bdbe4d612c7.html
 ✗ Failed to copyundefined
 ✗ Failed to copyundefined
 ✓ Copied [ utf8 ] src/index.poc1.html to runtime/.html
 ✓ Copied [ utf8 ] src/manifest.json to runtime/son
 ✗ Failed to copyundefined

Notice the name of copied files under runtime/ dir. Its somehow eating the file names.

**Comment by webextensions** [comment]
@vinodloha 
Please try with copy-files-from-to@1.4.0
It should work fine now.

Also note that the second pattern is slightly incorrect:
```js
// Notice the whitespace after comma, it should not be there
"../src/*.{html, js, json}"

// Kindly use this syntax
"../src/*.{html,js,json}"
```
