### ISSUE TITLE
Got some resourcePath bug

### ISSUE THREAD

**Issue by filmskent** [webextensions/copy-files-from-to#13]
I use the latest version 2.0.3 but it got bug like the picture below.
![Capture1](https://user-images.githubusercontent.com/21173050/61699791-c29ecd00-ad65-11e9-95e6-468797fb1d99.PNG)
![Capture2](https://user-images.githubusercontent.com/21173050/61699803-c6caea80-ad65-11e9-84db-fb77882ac066.PNG)

I try to use version 1.3.0 it's work. I think it maybe bug on Windows because Mac work on 2.0.3 . 
If I use something wrong please tell me thanks.

**Comment by webextensions** [comment]
@filmskent 

**Part 1**
I have improved the support for Windows OS and fixed a part of the problem you were facing. Please update to the latest version of [copy-files-from-to](https://www.npmjs.com/package/copy-files-from-to) (v2.1.0).

Fix: https://github.com/webextensions/copy-files-from-to/commit/de81bb63791af04d91a2d77d8119b20762204bb8

**Part 2**
Currently, providing a directory name is supported mainly for glob (wildcard) expressions only.
I would recommend you to use the following configuration to fix the remaining part of the issue:

```json
{
    "copyFiles": [
        {
            "from": "package.json",
            "to": "dist/package.json"
        },
        {
            "from": "README.md",
            "to": "dist/README.md"
        },
        {
            "from": "src/styles/**/*.less",
            "to": "dist/src/styles/"
        }
    ]
}
```

**Comment by filmskent** [comment]
Thanks @webextensions bug already fixed :D
