### ISSUE TITLE
It doesn't work with windows because of Unix path

### ISSUE THREAD

**Issue by mohouyizme** [webextensions/copy-files-from-to#2]
![screenshot_1](https://user-images.githubusercontent.com/23297439/40013677-c3c5fa60-579d-11e8-90f8-88855f39f25d.png)

**Comment by webextensions** [comment]
@mohouyizme Thanks for the report ... I'll fix that

**Comment by webextensions** [comment]
Fixed and published on npm:
https://github.com/webextensions/copy-files-from-to/commit/c42483179065ecd238b3152efe877724589e4717

copy-files-from-to@0.2.2
