### ISSUE TITLE
Not working when run in directory with parenthesis ``(`` in path 

### ISSUE THREAD

**Issue by marwie** [webextensions/copy-files-from-to#21]
Test path is ``C:\git\temp\Test (123)\Hello``

![20221118-093912_cmd-needle](https://user-images.githubusercontent.com/5083203/202658542-d52e277d-4dec-4481-8444-ba54d2041ac6.png)

Version ``"copy-files-from-to": "^3.2.2"``
script ``"copy-files": "copy-files-from-to"`` 
and config:
```json
"copyFiles": [
    {
      "from": "assets/**/*.*",
      "to": "dist/assets/"
    },
    {
      "from": "node_modules/@needle-tools/three/**/*.*",
      "to": "dist/include/"
    }
  ]
```

**Comment by webextensions** [comment]
@marwie 
Thank you for the report :+1: 

The issue has been fixed with https://github.com/webextensions/copy-files-from-to/commit/2c6e6256fe2661e2d60fae9d73018c3a71e60ee5 and it is available from copy-files-from-to@3.3.0 onwards.
