### ISSUE TITLE
Create directories when they dont exist?

### ISSUE THREAD

**Issue by marwie** [webextensions/copy-files-from-to#22]
Currently getting an error when a directory does not (yet) exist. 
Would it be possible to have copy file create those paths (maybe can be enabled by cli flag?)

![image](https://user-images.githubusercontent.com/5083203/214612208-0dd0d19e-5d4c-42a9-bc0c-720a5fa137b3.png)

**Comment by webextensions** [comment]
@marwie 
Thank you for the report.

Do you mean that the source file/directory ("from") is not available, but you wish to ignore that error? Do you still also wish to create the output directory path? If so, then can you describe the practical use-case, for identifying if that use-case is generic enough for adding to the library or can that be handled by a workaround (like ignoring errors when calling the `copy-files-from-to` command).

Is there anything more that you think would be useful to add context?

**Comment by marwie** [comment]
thanks for the quick reply

I mean "to" is not available. sorry i should have attached my package.json and more info.

We have a build process where we copy files from ``assets`` to ``dist/assets`` and ``inlude`` to ``dist/include``. 
The dist directories dont exist the first time we build in which case the ``failed to copy`` error is printed and the rest of the npm scripts dont run.

**Comment by webextensions** [comment]
@marwie

It seems to be the issue that `copy-files-from-to` doesn't support directory paths as the "from" input.

Seems to be that you are using it like:
```json
{
    "from": "dist/include",
    "to": "output/dist-include"
},
```

If you change it to the following (glob pattern), then it should work:
```json
{
    "from": "dist/include/**/*",
    "to": "output/dist-include"
},
```

For now, you should be able to get it to work.

**Let's keep this issue in Open state so that we follow up with the changes where the syntax that you had added would also work fine.**

**Comment by webextensions** [comment]
@marwie 

Now with the latest release (https://github.com/webextensions/copy-files-from-to/releases/tag/v3.7.0), support for copying directory has been added. You may now use the following syntax:
```js
// Copy the contents of the directory "src/app/images" to "public/assets"
{
    "from": "src/app/images",
    "to": "public/assets"
}
```

Marking resolved :+1:
