### ISSUE TITLE
Source Locations With Humongous Directory Structure Not Getting Copied Over Correctly

### ISSUE THREAD

**Issue by x80486** [webextensions/copy-files-from-to#29]
I installed `@shoelace-style/shoelace` version `2.15.1`.

I'm using the following block to copy over the distribution directory to some other location:

```javascript
{
  "from": "node_modules/@shoelace-style/shoelace/dist",
  "to": "static/@shoelace-style/shoelace/"
}
```

The problem is that the destination is getting somehow flattened — or something along those lines. It's definitely not a 1:1 copy with the source, and the `dist/` directory is skipped.

**Comment by x80486** [comment]
I'm using this (taken from an issue I saw) for the time being :sweat_smile:

```javascript
{
  "from": "node_modules/@shoelace-style/shoelace/dist/**/*.*",
  "to": "static/shoelace-style/shoelace/dist/"
},
```

**Comment by webextensions** [comment]
@x80486 
Great that you were able to find a solution / workaround.

As mentioned in https://github.com/webextensions/copy-files-from-to/issues/28#issuecomment-2190337786, we will ensure that this issue gets covered along with the change for that.

Closing this one.
