### ISSUE TITLE
Not able to minify any js

### ISSUE THREAD

**Issue by epikgit** [webextensions/copy-files-from-to#30]
Hi,
I'm going nut with this.
I'm using copy-files-from-to to create a distribution package from my dev folders.

This is my `package-copy-files-from-to.dist.cjson` configuration file:

    {
        "copyFiles": [
            {"from": 
                [
                    "./**/*", // Copy everything from the root folder except for...
                    "!dist/**/*", // the dist folder itself
                    "!node_modules/**/*", // the node_modules folder
                    "!./package*" // every file called package so and so
                ], 
                    "to": "dist/" 
            }
        ],
        "copyFilesSettings": {
            "whenFileExists": "overwrite",
            "removeSourceMappingURL": true,
            "minifyJs": true,
            "minifyJsTerserOptions": {
                "compress": true,
                "mangle": true,
                "format": {
                    "semicolons": false
                }
            }
        }
    }

And this is the command I'm using to launch the script:
`copy-files-from-to --config package-copy-files-from-to.dist.cjson`

What I'm expecting is that my *.js files are minified and copied in dist folder.
Unfortunately with any single configuration I tested, the files are correctly copied in dist but nothing happens regarding the minification.
Is it a bug?

I'm using copy-files-from-to version 3.11.0

**Comment by webextensions** [comment]
@epikgit 
Thank you for the report.

The bug is in the code around the line https://github.com/webextensions/copy-files-from-to/blob/5f952f9daf39b076bb6a71988e22b42ec22c2021/main.js#L214 where we are checking for the file extension in the "from" string which is a glob based pattern in the provided configuration.

We will attempt a fix for the reported issue.

**Comment by webextensions** [comment]
@epikgit
The fix is now available ([v3.12.0](https://www.npmjs.com/package/copy-files-from-to) onwards).

Hope it works fine now :smile:
