### ISSUE TITLE
Copy folder recursively

### ISSUE THREAD

**Issue by NicolasRoehm** [webextensions/copy-files-from-to#6]
I'm trying to copy all the content of a folder (other folders and files) to another location with the following `copy-files-from-to.json`.
```
{
  "copyFiles": [
    {
      "from": "assets/*",
      "to": "www/assets/*"
    }
  ]
}
```
Can we do that ? Thanks

**Comment by webextensions** [comment]
This issue has been fixed in the latest version ([copy-files-from-to@1.1.0](https://www.npmjs.com/package/copy-files-from-to)).

Please note that the ```to``` field should be the directory path (it shouldn't contain the "glob" pattern). So, the syntax would go like:

```
{
  "copyFiles": [
    {
      "from": "assets/*",
      "to": "www/assets/"
    }
  ]
}
```

**Comment by webextensions** [comment]
Please note that I have not tested the latest change on Windows. Hopefully, it should work fine :-)

In case you notice a bug, kindly add a comment and reopen.
