### ISSUE TITLE
copy gi

### ISSUE THREAD

**Issue by Thomas78180** [webextensions/copy-files-from-to#9]
copy loader.gif gives broken image

**Comment by mikko-tormala** [comment]
This is due to no support for binary files right now
The pull request I have in will fix that
https://github.com/webextensions/copy-files-from-to/pull/7

**Comment by Thomas78180** [comment]
Nice man ! Empressed to try it tomorrow after work. I'm sure it will be
good when i see your conclusion. See you tomorrow for greetings ;)

Le jeu. 4 avr. 2019 à 00:50, Mikko Tormala <notifications@github.com> a
écrit :

**Comment by Thomas78180** [comment]
> This is due to no support for binary files right now
> The pull request I have in will fix that
> #7

I'll use your fork ;)

**Comment by webextensions** [comment]
Marking closed since https://github.com/webextensions/copy-files-from-to/pull/7 has been merged :+1:
